[project]
name = "llvm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "customtkinter>=5.2.2",
    "fpdf>=1.7.2",
    "fastapi>=0.118.0",

]
